<?php

namespace ContainerCRmKJG8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__9HbLurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..9HbLur' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..9HbLur'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.VThUJXD', NULL, 'Cannot determine controller argument for "App\\Controller\\AdminController::editUser()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'user' => ['privates', '.errored.epWBlOW', NULL, 'Cannot determine controller argument for "App\\Controller\\AdminController::editUser()": the $user argument is type-hinted with the non-existent class or interface: "App\\Controller\\User". Did you forget to add a use statement?'],
        ], [
            'request' => '?',
            'user' => '?',
        ]);
    }
}
