<?php

namespace ContainerCRmKJG8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DishType' shared autowired service.
     *
     * @return \App\Form\DishType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DishType.php';

        return $container->privates['App\\Form\\DishType'] = new \App\Form\DishType();
    }
}
