<?php

namespace ContainerCRmKJG8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TC4F5Tj.App\Entity\Dish' shared service.
     *
     * @return \App\Entity\Dish
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TC4F5Tj": it references class "App\\Entity\\Dish" but no such service exists.');
    }
}
